### ISSUE TITLE
Create video page

### ISSUE THREAD

**Issue by AbhayChandel** [AbhayChandel/drool-vue-client#43]
Following issues need to be completed part of this feature

- [x] Issue #42 (Build video page template)

- [x] Issue https://github.com/AbhayChandel/drool-vue-client/issues/44 (Toggle video like button)

- [x] Issue https://github.com/AbhayChandel/drool-vue-client/issues/45 (New comment)

- [x] Issue https://github.com/AbhayChandel/drool-vue-client/issues/47 (Toggle comment like)

- [x] Issue #48 (View video comment list)

- [x] Issue #71 (Create video edit page)

**Comment by AbhayChandel** [comment]
Issue #42 implemented with PR https://github.com/AbhayChandel/drool-vue-client/pull/49
